// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetServiceHistoryHandlerFunc turns a function with the right signature into a get service history handler
type GetServiceHistoryHandlerFunc func(GetServiceHistoryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetServiceHistoryHandlerFunc) Handle(params GetServiceHistoryParams) middleware.Responder {
	return fn(params)
}

// GetServiceHistoryHandler interface for that can handle valid get service history params
type GetServiceHistoryHandler interface {
	Handle(GetServiceHistoryParams) middleware.Responder
}

// NewGetServiceHistory creates a new http.Handler for the get service history operation
func NewGetServiceHistory(ctx *middleware.Context, handler GetServiceHistoryHandler) *GetServiceHistory {
	return &GetServiceHistory{Context: ctx, Handler: handler}
}

/*GetServiceHistory swagger:route GET /api/v1/groups/{groupname}/runtime/apps/{appname}/service/history service getServiceHistory

GetServiceHistory get service history API

*/
type GetServiceHistory struct {
	Context *middleware.Context
	Handler GetServiceHistoryHandler
}

func (o *GetServiceHistory) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetServiceHistoryParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
