// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/laincloud/console-api/models"
)

// GetServiceHistoryOKCode is the HTTP code returned for type GetServiceHistoryOK
const GetServiceHistoryOKCode int = 200

/*GetServiceHistoryOK Get the service history of the runtime app

swagger:response getServiceHistoryOK
*/
type GetServiceHistoryOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Service `json:"body,omitempty"`
}

// NewGetServiceHistoryOK creates GetServiceHistoryOK with default headers values
func NewGetServiceHistoryOK() *GetServiceHistoryOK {

	return &GetServiceHistoryOK{}
}

// WithPayload adds the payload to the get service history o k response
func (o *GetServiceHistoryOK) WithPayload(payload []*models.Service) *GetServiceHistoryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get service history o k response
func (o *GetServiceHistoryOK) SetPayload(payload []*models.Service) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetServiceHistoryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Service, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetServiceHistoryDefault Failed

swagger:response getServiceHistoryDefault
*/
type GetServiceHistoryDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetServiceHistoryDefault creates GetServiceHistoryDefault with default headers values
func NewGetServiceHistoryDefault(code int) *GetServiceHistoryDefault {
	if code <= 0 {
		code = 500
	}

	return &GetServiceHistoryDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get service history default response
func (o *GetServiceHistoryDefault) WithStatusCode(code int) *GetServiceHistoryDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get service history default response
func (o *GetServiceHistoryDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get service history default response
func (o *GetServiceHistoryDefault) WithPayload(payload *models.Error) *GetServiceHistoryDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get service history default response
func (o *GetServiceHistoryDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetServiceHistoryDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
