// Code generated by go-swagger; DO NOT EDIT.

package services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/laincloud/console-api/models"
)

// CreateOrUpdateServicesOKCode is the HTTP code returned for type CreateOrUpdateServicesOK
const CreateOrUpdateServicesOKCode int = 200

/*CreateOrUpdateServicesOK OK

swagger:response createOrUpdateServicesOK
*/
type CreateOrUpdateServicesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Service `json:"body,omitempty"`
}

// NewCreateOrUpdateServicesOK creates CreateOrUpdateServicesOK with default headers values
func NewCreateOrUpdateServicesOK() *CreateOrUpdateServicesOK {

	return &CreateOrUpdateServicesOK{}
}

// WithPayload adds the payload to the create or update services o k response
func (o *CreateOrUpdateServicesOK) WithPayload(payload []*models.Service) *CreateOrUpdateServicesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create or update services o k response
func (o *CreateOrUpdateServicesOK) SetPayload(payload []*models.Service) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateOrUpdateServicesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Service, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*CreateOrUpdateServicesDefault Failed

swagger:response createOrUpdateServicesDefault
*/
type CreateOrUpdateServicesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateOrUpdateServicesDefault creates CreateOrUpdateServicesDefault with default headers values
func NewCreateOrUpdateServicesDefault(code int) *CreateOrUpdateServicesDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateOrUpdateServicesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create or update services default response
func (o *CreateOrUpdateServicesDefault) WithStatusCode(code int) *CreateOrUpdateServicesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create or update services default response
func (o *CreateOrUpdateServicesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create or update services default response
func (o *CreateOrUpdateServicesDefault) WithPayload(payload *models.Error) *CreateOrUpdateServicesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create or update services default response
func (o *CreateOrUpdateServicesDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateOrUpdateServicesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
