// Code generated by go-swagger; DO NOT EDIT.

package services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetServicesHistoryHandlerFunc turns a function with the right signature into a get services history handler
type GetServicesHistoryHandlerFunc func(GetServicesHistoryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetServicesHistoryHandlerFunc) Handle(params GetServicesHistoryParams) middleware.Responder {
	return fn(params)
}

// GetServicesHistoryHandler interface for that can handle valid get services history params
type GetServicesHistoryHandler interface {
	Handle(GetServicesHistoryParams) middleware.Responder
}

// NewGetServicesHistory creates a new http.Handler for the get services history operation
func NewGetServicesHistory(ctx *middleware.Context, handler GetServicesHistoryHandler) *GetServicesHistory {
	return &GetServicesHistory{Context: ctx, Handler: handler}
}

/*GetServicesHistory swagger:route GET /api/v1/groups/{groupname}/runtimeapps/{appname}/services/history services getServicesHistory

GetServicesHistory get services history API

*/
type GetServicesHistory struct {
	Context *middleware.Context
	Handler GetServicesHistoryHandler
}

func (o *GetServicesHistory) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetServicesHistoryParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
