// Code generated by go-swagger; DO NOT EDIT.

package services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/laincloud/console-api/models"
)

// GetServicesHistoryOKCode is the HTTP code returned for type GetServicesHistoryOK
const GetServicesHistoryOKCode int = 200

/*GetServicesHistoryOK Get the services history of the runtime app

swagger:response getServicesHistoryOK
*/
type GetServicesHistoryOK struct {

	/*
	  In: Body
	*/
	Payload [][]*models.Service `json:"body,omitempty"`
}

// NewGetServicesHistoryOK creates GetServicesHistoryOK with default headers values
func NewGetServicesHistoryOK() *GetServicesHistoryOK {

	return &GetServicesHistoryOK{}
}

// WithPayload adds the payload to the get services history o k response
func (o *GetServicesHistoryOK) WithPayload(payload [][]*models.Service) *GetServicesHistoryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get services history o k response
func (o *GetServicesHistoryOK) SetPayload(payload [][]*models.Service) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetServicesHistoryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([][]*models.Service, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetServicesHistoryDefault Failed

swagger:response getServicesHistoryDefault
*/
type GetServicesHistoryDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetServicesHistoryDefault creates GetServicesHistoryDefault with default headers values
func NewGetServicesHistoryDefault(code int) *GetServicesHistoryDefault {
	if code <= 0 {
		code = 500
	}

	return &GetServicesHistoryDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get services history default response
func (o *GetServicesHistoryDefault) WithStatusCode(code int) *GetServicesHistoryDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get services history default response
func (o *GetServicesHistoryDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get services history default response
func (o *GetServicesHistoryDefault) WithPayload(payload *models.Error) *GetServicesHistoryDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get services history default response
func (o *GetServicesHistoryDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetServicesHistoryDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
