// Code generated by go-swagger; DO NOT EDIT.

package deployment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/laincloud/console-api/models"
)

// GetDeploymentOKCode is the HTTP code returned for type GetDeploymentOK
const GetDeploymentOKCode int = 200

/*GetDeploymentOK Get a deployment

swagger:response getDeploymentOK
*/
type GetDeploymentOK struct {

	/*
	  In: Body
	*/
	Payload *models.App `json:"body,omitempty"`
}

// NewGetDeploymentOK creates GetDeploymentOK with default headers values
func NewGetDeploymentOK() *GetDeploymentOK {

	return &GetDeploymentOK{}
}

// WithPayload adds the payload to the get deployment o k response
func (o *GetDeploymentOK) WithPayload(payload *models.App) *GetDeploymentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get deployment o k response
func (o *GetDeploymentOK) SetPayload(payload *models.App) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDeploymentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
