swagger: "2.0"

info:
  description: The Console API Server for LAIN Cluster
  title: Console
  version: 0.0.1

schemes:
  - http

consumes:
  - application/vnd.laincloud.console.v1+json

produces:
  - application/vnd.laincloud.console.v1+json

paths:
  /ping:
    get:
      tags:
        - ping
      responses:
        200:
          description: Check whether the server is healthy

  /groups:
    post:
      tags:
        - groups
      operationId: createGroup
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/group"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/group"
        default:
          description: Failed
          schema:
            $ref: "#/definitions/error"
    get:
      tags:
        - groups
      operationId: getGroups
      responses:
        200:
          description: List the groups
          schema:
            type: array
            items:
              $ref: "#/definitions/group"
        default:
          description: Failed
          schema:
            $ref: "#/definitions/error"
  /groups/{group}:
    parameters:
      - type: integer
        format: int64
        name: group
        in: path
        required: true
    get:
      tags:
        - groups
      operationId: getGroup
      responses:
        200:
          description: Get one group
          schema:
            $ref: "#/definitions/group"
    put:
      tags:
        - groups
      operationId: updateGroup
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/group"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/group"
        default:
          description: Failed
          schema:
            $ref: "#/definitions/error"
    delete:
      tags:
        - groups
      operationId: deleteGroup
      responses:
        204:
          description: Deleted
        default:
          description: Failed
          schema:
            $ref: "#/definitions/error"

  /groups/{group}/apps:
    parameters:
      - type: integer
        format: int64
        name: group
        in: path
        required: true
    post:
      tags:
        - apps
      operationId: createApp
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/app"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/app"
        default:
          description: Failed
          schema:
            $ref: "#/definitions/error"
    get:
      tags:
        - apps
      operationId: getApps
      responses:
        200:
          description: List the apps
          schema:
            type: array
            items:
              $ref: "#/definitions/app"
        default:
          description: Failed
          schema:
            $ref: "#/definitions/error"
  /groups/{group}/apps/{app}:
    parameters:
      - type: integer
        format: int64
        name: group
        in: path
        required: true
      - type: integer
        format: int64
        name: app
        in: path
        required: true
    get:
      tags:
        - apps
      operationId: getApp
      responses:
        200:
          description: Get one App
          schema:
            $ref: "#/definitions/app"
    put:
      tags:
        - apps
      operationId: updateApp
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/app"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/app"
        default:
          description: Failed
          schema:
            $ref: "#/definitions/error"
    delete:
      tags:
        - apps
      operationId: deleteApp
      responses:
        204:
          description: Deleted
        default:
          description: Failed
          schema:
            $ref: "#/definitions/error"

  /groups/{group}/apps/{app}/deployment:
    parameters:
      - type: integer
        format: int64
        name: group
        in: path
        required: true
      - type: integer
        format: int64
        name: app
        in: path
        required: true
    get:
      tags:
        - deployment
      operationId: getDeployment
      responses:
        200:
          description: Get a deployment
          schema:
            $ref: "#/definitions/app"

definitions:
  error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
        minLength: 1

  group:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      name:
        type: string
        minLength: 1
      description:
        type: string
        minLength: 1

  app:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      name:
        type: string
        minLength: 1
      owner:
        type: string
        minLength: 1
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time

  deployment:
    type: object
