// Code generated by go-swagger; DO NOT EDIT.

package cluster_resource_usage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetClusterResourceHandlerFunc turns a function with the right signature into a get cluster resource handler
type GetClusterResourceHandlerFunc func(GetClusterResourceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetClusterResourceHandlerFunc) Handle(params GetClusterResourceParams) middleware.Responder {
	return fn(params)
}

// GetClusterResourceHandler interface for that can handle valid get cluster resource params
type GetClusterResourceHandler interface {
	Handle(GetClusterResourceParams) middleware.Responder
}

// NewGetClusterResource creates a new http.Handler for the get cluster resource operation
func NewGetClusterResource(ctx *middleware.Context, handler GetClusterResourceHandler) *GetClusterResource {
	return &GetClusterResource{Context: ctx, Handler: handler}
}

/*GetClusterResource swagger:route GET /api/v1/cluster/resourceusage clusterResourceUsage getClusterResource

GetClusterResource get cluster resource API

*/
type GetClusterResource struct {
	Context *middleware.Context
	Handler GetClusterResourceHandler
}

func (o *GetClusterResource) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetClusterResourceParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
