// Code generated by go-swagger; DO NOT EDIT.

package pvcs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreatePVCHandlerFunc turns a function with the right signature into a create p v c handler
type CreatePVCHandlerFunc func(CreatePVCParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreatePVCHandlerFunc) Handle(params CreatePVCParams) middleware.Responder {
	return fn(params)
}

// CreatePVCHandler interface for that can handle valid create p v c params
type CreatePVCHandler interface {
	Handle(CreatePVCParams) middleware.Responder
}

// NewCreatePVC creates a new http.Handler for the create p v c operation
func NewCreatePVC(ctx *middleware.Context, handler CreatePVCHandler) *CreatePVC {
	return &CreatePVC{Context: ctx, Handler: handler}
}

/*CreatePVC swagger:route POST /api/v1/groups/{groupname}/runtime/pvcs pvcs createPVC

CreatePVC create p v c API

*/
type CreatePVC struct {
	Context *middleware.Context
	Handler CreatePVCHandler
}

func (o *CreatePVC) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreatePVCParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
