// Code generated by go-swagger; DO NOT EDIT.

package pvcs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/laincloud/console-api/models"
)

// DeletePVCNoContentCode is the HTTP code returned for type DeletePVCNoContent
const DeletePVCNoContentCode int = 204

/*DeletePVCNoContent Deleted

swagger:response deletePVCNoContent
*/
type DeletePVCNoContent struct {
}

// NewDeletePVCNoContent creates DeletePVCNoContent with default headers values
func NewDeletePVCNoContent() *DeletePVCNoContent {

	return &DeletePVCNoContent{}
}

// WriteResponse to the client
func (o *DeletePVCNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*DeletePVCDefault Failed

swagger:response deletePVCDefault
*/
type DeletePVCDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeletePVCDefault creates DeletePVCDefault with default headers values
func NewDeletePVCDefault(code int) *DeletePVCDefault {
	if code <= 0 {
		code = 500
	}

	return &DeletePVCDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete p v c default response
func (o *DeletePVCDefault) WithStatusCode(code int) *DeletePVCDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete p v c default response
func (o *DeletePVCDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete p v c default response
func (o *DeletePVCDefault) WithPayload(payload *models.Error) *DeletePVCDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete p v c default response
func (o *DeletePVCDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletePVCDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
