// Code generated by go-swagger; DO NOT EDIT.

package pvcs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeletePVCParams creates a new DeletePVCParams object
// no default values defined in spec.
func NewDeletePVCParams() DeletePVCParams {

	return DeletePVCParams{}
}

// DeletePVCParams contains all the bound params for the delete p v c operation
// typically these are obtained from a http.Request
//
// swagger:parameters deletePVC
type DeletePVCParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  Min Length: 1
	  In: path
	*/
	Groupname string
	/*
	  Required: true
	  Min Length: 1
	  In: path
	*/
	Pvcname string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeletePVCParams() beforehand.
func (o *DeletePVCParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rGroupname, rhkGroupname, _ := route.Params.GetOK("groupname")
	if err := o.bindGroupname(rGroupname, rhkGroupname, route.Formats); err != nil {
		res = append(res, err)
	}

	rPvcname, rhkPvcname, _ := route.Params.GetOK("pvcname")
	if err := o.bindPvcname(rPvcname, rhkPvcname, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeletePVCParams) bindGroupname(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Groupname = raw

	if err := o.validateGroupname(formats); err != nil {
		return err
	}

	return nil
}

func (o *DeletePVCParams) validateGroupname(formats strfmt.Registry) error {

	if err := validate.MinLength("groupname", "path", o.Groupname, 1); err != nil {
		return err
	}

	return nil
}

func (o *DeletePVCParams) bindPvcname(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Pvcname = raw

	if err := o.validatePvcname(formats); err != nil {
		return err
	}

	return nil
}

func (o *DeletePVCParams) validatePvcname(formats strfmt.Registry) error {

	if err := validate.MinLength("pvcname", "path", o.Pvcname, 1); err != nil {
		return err
	}

	return nil
}
