// Code generated by go-swagger; DO NOT EDIT.

package pvcs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/laincloud/console-api/models"
)

// GetPVCOKCode is the HTTP code returned for type GetPVCOK
const GetPVCOKCode int = 200

/*GetPVCOK Get the PVC

swagger:response getPVCOK
*/
type GetPVCOK struct {

	/*
	  In: Body
	*/
	Payload models.Pvc `json:"body,omitempty"`
}

// NewGetPVCOK creates GetPVCOK with default headers values
func NewGetPVCOK() *GetPVCOK {

	return &GetPVCOK{}
}

// WithPayload adds the payload to the get p v c o k response
func (o *GetPVCOK) WithPayload(payload models.Pvc) *GetPVCOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get p v c o k response
func (o *GetPVCOK) SetPayload(payload models.Pvc) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPVCOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetPVCDefault Failed

swagger:response getPVCDefault
*/
type GetPVCDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetPVCDefault creates GetPVCDefault with default headers values
func NewGetPVCDefault(code int) *GetPVCDefault {
	if code <= 0 {
		code = 500
	}

	return &GetPVCDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get p v c default response
func (o *GetPVCDefault) WithStatusCode(code int) *GetPVCDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get p v c default response
func (o *GetPVCDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get p v c default response
func (o *GetPVCDefault) WithPayload(payload *models.Error) *GetPVCDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get p v c default response
func (o *GetPVCDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPVCDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
