// Code generated by go-swagger; DO NOT EDIT.

package pvcs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/laincloud/console-api/models"
)

// UpdatePVCOKCode is the HTTP code returned for type UpdatePVCOK
const UpdatePVCOKCode int = 200

/*UpdatePVCOK OK

swagger:response updatePVCOK
*/
type UpdatePVCOK struct {

	/*
	  In: Body
	*/
	Payload models.Pvc `json:"body,omitempty"`
}

// NewUpdatePVCOK creates UpdatePVCOK with default headers values
func NewUpdatePVCOK() *UpdatePVCOK {

	return &UpdatePVCOK{}
}

// WithPayload adds the payload to the update p v c o k response
func (o *UpdatePVCOK) WithPayload(payload models.Pvc) *UpdatePVCOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update p v c o k response
func (o *UpdatePVCOK) SetPayload(payload models.Pvc) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdatePVCOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*UpdatePVCDefault Failed

swagger:response updatePVCDefault
*/
type UpdatePVCDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdatePVCDefault creates UpdatePVCDefault with default headers values
func NewUpdatePVCDefault(code int) *UpdatePVCDefault {
	if code <= 0 {
		code = 500
	}

	return &UpdatePVCDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the update p v c default response
func (o *UpdatePVCDefault) WithStatusCode(code int) *UpdatePVCDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the update p v c default response
func (o *UpdatePVCDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the update p v c default response
func (o *UpdatePVCDefault) WithPayload(payload *models.Error) *UpdatePVCDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update p v c default response
func (o *UpdatePVCDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdatePVCDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
