// Code generated by go-swagger; DO NOT EDIT.

package runtime_app_secret

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetRuntimeAppSecretHistoryHandlerFunc turns a function with the right signature into a get runtime app secret history handler
type GetRuntimeAppSecretHistoryHandlerFunc func(GetRuntimeAppSecretHistoryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRuntimeAppSecretHistoryHandlerFunc) Handle(params GetRuntimeAppSecretHistoryParams) middleware.Responder {
	return fn(params)
}

// GetRuntimeAppSecretHistoryHandler interface for that can handle valid get runtime app secret history params
type GetRuntimeAppSecretHistoryHandler interface {
	Handle(GetRuntimeAppSecretHistoryParams) middleware.Responder
}

// NewGetRuntimeAppSecretHistory creates a new http.Handler for the get runtime app secret history operation
func NewGetRuntimeAppSecretHistory(ctx *middleware.Context, handler GetRuntimeAppSecretHistoryHandler) *GetRuntimeAppSecretHistory {
	return &GetRuntimeAppSecretHistory{Context: ctx, Handler: handler}
}

/*GetRuntimeAppSecretHistory swagger:route GET /api/v1/groups/{groupname}/runtime/apps/{appname}/secrets/{secretname}/history runtimeAppSecret getRuntimeAppSecretHistory

GetRuntimeAppSecretHistory get runtime app secret history API

*/
type GetRuntimeAppSecretHistory struct {
	Context *middleware.Context
	Handler GetRuntimeAppSecretHistoryHandler
}

func (o *GetRuntimeAppSecretHistory) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetRuntimeAppSecretHistoryParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
