// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Console
The Console API Server for LAIN Cluster


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 0.0.1

    Consumes:
    - application/vnd.laincloud.console.v1+json

    Produces:
    - application/vnd.laincloud.console.v1+json

swagger:meta
*/
package restapi
