// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/vnd.laincloud.console.v1+json"
  ],
  "produces": [
    "application/vnd.laincloud.console.v1+json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "The Console for LAIN Cluster",
    "title": "Console",
    "version": "0.0.1"
  },
  "paths": {
    "/ping": {
      "get": {
        "tags": [
          "ping"
        ],
        "responses": {
          "200": {
            "description": "check whether it is healthy"
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/vnd.laincloud.console.v1+json"
  ],
  "produces": [
    "application/vnd.laincloud.console.v1+json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "The Console for LAIN Cluster",
    "title": "Console",
    "version": "0.0.1"
  },
  "paths": {
    "/ping": {
      "get": {
        "tags": [
          "ping"
        ],
        "responses": {
          "200": {
            "description": "check whether it is healthy"
          }
        }
      }
    }
  }
}`))
}
