// Code generated by go-swagger; DO NOT EDIT.

package ingress

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateOrUpdateIngressHandlerFunc turns a function with the right signature into a create or update ingress handler
type CreateOrUpdateIngressHandlerFunc func(CreateOrUpdateIngressParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateOrUpdateIngressHandlerFunc) Handle(params CreateOrUpdateIngressParams) middleware.Responder {
	return fn(params)
}

// CreateOrUpdateIngressHandler interface for that can handle valid create or update ingress params
type CreateOrUpdateIngressHandler interface {
	Handle(CreateOrUpdateIngressParams) middleware.Responder
}

// NewCreateOrUpdateIngress creates a new http.Handler for the create or update ingress operation
func NewCreateOrUpdateIngress(ctx *middleware.Context, handler CreateOrUpdateIngressHandler) *CreateOrUpdateIngress {
	return &CreateOrUpdateIngress{Context: ctx, Handler: handler}
}

/*CreateOrUpdateIngress swagger:route PUT /api/v1/groups/{groupname}/runtime/ingress ingress createOrUpdateIngress

CreateOrUpdateIngress create or update ingress API

*/
type CreateOrUpdateIngress struct {
	Context *middleware.Context
	Handler CreateOrUpdateIngressHandler
}

func (o *CreateOrUpdateIngress) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateOrUpdateIngressParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
