// Code generated by go-swagger; DO NOT EDIT.

package ingress

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/laincloud/console-api/models"
)

// GetIngressOKCode is the HTTP code returned for type GetIngressOK
const GetIngressOKCode int = 200

/*GetIngressOK Get the ingress

swagger:response getIngressOK
*/
type GetIngressOK struct {

	/*
	  In: Body
	*/
	Payload *models.Ingress `json:"body,omitempty"`
}

// NewGetIngressOK creates GetIngressOK with default headers values
func NewGetIngressOK() *GetIngressOK {

	return &GetIngressOK{}
}

// WithPayload adds the payload to the get ingress o k response
func (o *GetIngressOK) WithPayload(payload *models.Ingress) *GetIngressOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get ingress o k response
func (o *GetIngressOK) SetPayload(payload *models.Ingress) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetIngressOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetIngressDefault Failed

swagger:response getIngressDefault
*/
type GetIngressDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetIngressDefault creates GetIngressDefault with default headers values
func NewGetIngressDefault(code int) *GetIngressDefault {
	if code <= 0 {
		code = 500
	}

	return &GetIngressDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get ingress default response
func (o *GetIngressDefault) WithStatusCode(code int) *GetIngressDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get ingress default response
func (o *GetIngressDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get ingress default response
func (o *GetIngressDefault) WithPayload(payload *models.Error) *GetIngressDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get ingress default response
func (o *GetIngressDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetIngressDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
