// Code generated by go-swagger; DO NOT EDIT.

package build_apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/laincloud/console-api/models"
)

// CreateBuildAppCreatedCode is the HTTP code returned for type CreateBuildAppCreated
const CreateBuildAppCreatedCode int = 201

/*CreateBuildAppCreated Created

swagger:response createBuildAppCreated
*/
type CreateBuildAppCreated struct {

	/*
	  In: Body
	*/
	Payload *models.BuildApp `json:"body,omitempty"`
}

// NewCreateBuildAppCreated creates CreateBuildAppCreated with default headers values
func NewCreateBuildAppCreated() *CreateBuildAppCreated {

	return &CreateBuildAppCreated{}
}

// WithPayload adds the payload to the create build app created response
func (o *CreateBuildAppCreated) WithPayload(payload *models.BuildApp) *CreateBuildAppCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create build app created response
func (o *CreateBuildAppCreated) SetPayload(payload *models.BuildApp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateBuildAppCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*CreateBuildAppDefault Failed

swagger:response createBuildAppDefault
*/
type CreateBuildAppDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateBuildAppDefault creates CreateBuildAppDefault with default headers values
func NewCreateBuildAppDefault(code int) *CreateBuildAppDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateBuildAppDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create build app default response
func (o *CreateBuildAppDefault) WithStatusCode(code int) *CreateBuildAppDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create build app default response
func (o *CreateBuildAppDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create build app default response
func (o *CreateBuildAppDefault) WithPayload(payload *models.Error) *CreateBuildAppDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create build app default response
func (o *CreateBuildAppDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateBuildAppDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
