// Code generated by go-swagger; DO NOT EDIT.

package build_apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/laincloud/console-api/models"
)

// GetBuildAppOKCode is the HTTP code returned for type GetBuildAppOK
const GetBuildAppOKCode int = 200

/*GetBuildAppOK Get the build App

swagger:response getBuildAppOK
*/
type GetBuildAppOK struct {

	/*
	  In: Body
	*/
	Payload *models.BuildApp `json:"body,omitempty"`
}

// NewGetBuildAppOK creates GetBuildAppOK with default headers values
func NewGetBuildAppOK() *GetBuildAppOK {

	return &GetBuildAppOK{}
}

// WithPayload adds the payload to the get build app o k response
func (o *GetBuildAppOK) WithPayload(payload *models.BuildApp) *GetBuildAppOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get build app o k response
func (o *GetBuildAppOK) SetPayload(payload *models.BuildApp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBuildAppOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetBuildAppDefault Failed

swagger:response getBuildAppDefault
*/
type GetBuildAppDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBuildAppDefault creates GetBuildAppDefault with default headers values
func NewGetBuildAppDefault(code int) *GetBuildAppDefault {
	if code <= 0 {
		code = 500
	}

	return &GetBuildAppDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get build app default response
func (o *GetBuildAppDefault) WithStatusCode(code int) *GetBuildAppDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get build app default response
func (o *GetBuildAppDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get build app default response
func (o *GetBuildAppDefault) WithPayload(payload *models.Error) *GetBuildAppDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get build app default response
func (o *GetBuildAppDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBuildAppDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
