// Code generated by go-swagger; DO NOT EDIT.

package build_apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/laincloud/console-api/models"
)

// GetBuildAppsOKCode is the HTTP code returned for type GetBuildAppsOK
const GetBuildAppsOKCode int = 200

/*GetBuildAppsOK List the build apps

swagger:response getBuildAppsOK
*/
type GetBuildAppsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.BuildApp `json:"body,omitempty"`
}

// NewGetBuildAppsOK creates GetBuildAppsOK with default headers values
func NewGetBuildAppsOK() *GetBuildAppsOK {

	return &GetBuildAppsOK{}
}

// WithPayload adds the payload to the get build apps o k response
func (o *GetBuildAppsOK) WithPayload(payload []*models.BuildApp) *GetBuildAppsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get build apps o k response
func (o *GetBuildAppsOK) SetPayload(payload []*models.BuildApp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBuildAppsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.BuildApp, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetBuildAppsDefault Failed

swagger:response getBuildAppsDefault
*/
type GetBuildAppsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBuildAppsDefault creates GetBuildAppsDefault with default headers values
func NewGetBuildAppsDefault(code int) *GetBuildAppsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetBuildAppsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get build apps default response
func (o *GetBuildAppsDefault) WithStatusCode(code int) *GetBuildAppsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get build apps default response
func (o *GetBuildAppsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get build apps default response
func (o *GetBuildAppsDefault) WithPayload(payload *models.Error) *GetBuildAppsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get build apps default response
func (o *GetBuildAppsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBuildAppsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
