// Code generated by go-swagger; DO NOT EDIT.

package ping

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/laincloud/console-api/models"
)

// GetAPIV1PingOKCode is the HTTP code returned for type GetAPIV1PingOK
const GetAPIV1PingOKCode int = 200

/*GetAPIV1PingOK Check whether the server is healthy

swagger:response getApiV1PingOK
*/
type GetAPIV1PingOK struct {
}

// NewGetAPIV1PingOK creates GetAPIV1PingOK with default headers values
func NewGetAPIV1PingOK() *GetAPIV1PingOK {

	return &GetAPIV1PingOK{}
}

// WriteResponse to the client
func (o *GetAPIV1PingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*GetAPIV1PingDefault Failed

swagger:response getApiV1PingDefault
*/
type GetAPIV1PingDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAPIV1PingDefault creates GetAPIV1PingDefault with default headers values
func NewGetAPIV1PingDefault(code int) *GetAPIV1PingDefault {
	if code <= 0 {
		code = 500
	}

	return &GetAPIV1PingDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get API v1 ping default response
func (o *GetAPIV1PingDefault) WithStatusCode(code int) *GetAPIV1PingDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get API v1 ping default response
func (o *GetAPIV1PingDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get API v1 ping default response
func (o *GetAPIV1PingDefault) WithPayload(payload *models.Error) *GetAPIV1PingDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get API v1 ping default response
func (o *GetAPIV1PingDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAPIV1PingDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
