// Code generated by go-swagger; DO NOT EDIT.

package config_map

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetConfigMapHandlerFunc turns a function with the right signature into a get config map handler
type GetConfigMapHandlerFunc func(GetConfigMapParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetConfigMapHandlerFunc) Handle(params GetConfigMapParams) middleware.Responder {
	return fn(params)
}

// GetConfigMapHandler interface for that can handle valid get config map params
type GetConfigMapHandler interface {
	Handle(GetConfigMapParams) middleware.Responder
}

// NewGetConfigMap creates a new http.Handler for the get config map operation
func NewGetConfigMap(ctx *middleware.Context, handler GetConfigMapHandler) *GetConfigMap {
	return &GetConfigMap{Context: ctx, Handler: handler}
}

/*GetConfigMap swagger:route GET /api/v1/groups/{groupname}/runtime/apps/{appname}/configmap configMap getConfigMap

GetConfigMap get config map API

*/
type GetConfigMap struct {
	Context *middleware.Context
	Handler GetConfigMapHandler
}

func (o *GetConfigMap) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetConfigMapParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
