// Code generated by go-swagger; DO NOT EDIT.

package runtime_app_secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/laincloud/console-api/models"
)

// DeleteRuntimeAppSecretNoContentCode is the HTTP code returned for type DeleteRuntimeAppSecretNoContent
const DeleteRuntimeAppSecretNoContentCode int = 204

/*DeleteRuntimeAppSecretNoContent Deleted

swagger:response deleteRuntimeAppSecretNoContent
*/
type DeleteRuntimeAppSecretNoContent struct {
}

// NewDeleteRuntimeAppSecretNoContent creates DeleteRuntimeAppSecretNoContent with default headers values
func NewDeleteRuntimeAppSecretNoContent() *DeleteRuntimeAppSecretNoContent {

	return &DeleteRuntimeAppSecretNoContent{}
}

// WriteResponse to the client
func (o *DeleteRuntimeAppSecretNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*DeleteRuntimeAppSecretDefault Failed

swagger:response deleteRuntimeAppSecretDefault
*/
type DeleteRuntimeAppSecretDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteRuntimeAppSecretDefault creates DeleteRuntimeAppSecretDefault with default headers values
func NewDeleteRuntimeAppSecretDefault(code int) *DeleteRuntimeAppSecretDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteRuntimeAppSecretDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete runtime app secret default response
func (o *DeleteRuntimeAppSecretDefault) WithStatusCode(code int) *DeleteRuntimeAppSecretDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete runtime app secret default response
func (o *DeleteRuntimeAppSecretDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete runtime app secret default response
func (o *DeleteRuntimeAppSecretDefault) WithPayload(payload *models.Error) *DeleteRuntimeAppSecretDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete runtime app secret default response
func (o *DeleteRuntimeAppSecretDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteRuntimeAppSecretDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
