// Code generated by go-swagger; DO NOT EDIT.

package builds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetBuildPublishmentsHandlerFunc turns a function with the right signature into a get build publishments handler
type GetBuildPublishmentsHandlerFunc func(GetBuildPublishmentsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBuildPublishmentsHandlerFunc) Handle(params GetBuildPublishmentsParams) middleware.Responder {
	return fn(params)
}

// GetBuildPublishmentsHandler interface for that can handle valid get build publishments params
type GetBuildPublishmentsHandler interface {
	Handle(GetBuildPublishmentsParams) middleware.Responder
}

// NewGetBuildPublishments creates a new http.Handler for the get build publishments operation
func NewGetBuildPublishments(ctx *middleware.Context, handler GetBuildPublishmentsHandler) *GetBuildPublishments {
	return &GetBuildPublishments{Context: ctx, Handler: handler}
}

/*GetBuildPublishments swagger:route GET /api/v1/groups/{groupname}/build/apps/{appname}/builds/{buildid}/publishments builds getBuildPublishments

GetBuildPublishments get build publishments API

*/
type GetBuildPublishments struct {
	Context *middleware.Context
	Handler GetBuildPublishmentsHandler
}

func (o *GetBuildPublishments) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetBuildPublishmentsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
