// Code generated by go-swagger; DO NOT EDIT.

package builds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetBuildLogHandlerFunc turns a function with the right signature into a get build log handler
type GetBuildLogHandlerFunc func(GetBuildLogParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBuildLogHandlerFunc) Handle(params GetBuildLogParams) middleware.Responder {
	return fn(params)
}

// GetBuildLogHandler interface for that can handle valid get build log params
type GetBuildLogHandler interface {
	Handle(GetBuildLogParams) middleware.Responder
}

// NewGetBuildLog creates a new http.Handler for the get build log operation
func NewGetBuildLog(ctx *middleware.Context, handler GetBuildLogHandler) *GetBuildLog {
	return &GetBuildLog{Context: ctx, Handler: handler}
}

/*GetBuildLog swagger:route GET /api/v1/groups/{groupname}/build/apps/{appname}/builds/{buildid}/log builds getBuildLog

GetBuildLog get build log API

*/
type GetBuildLog struct {
	Context *middleware.Context
	Handler GetBuildLogHandler
}

func (o *GetBuildLog) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetBuildLogParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
