// Code generated by go-swagger; DO NOT EDIT.

package workload

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/laincloud/console-api/models"
)

// GetConfigMapHistoryOKCode is the HTTP code returned for type GetConfigMapHistoryOK
const GetConfigMapHistoryOKCode int = 200

/*GetConfigMapHistoryOK Get the config map history of the runtime app

swagger:response getConfigMapHistoryOK
*/
type GetConfigMapHistoryOK struct {

	/*
	  In: Body
	*/
	Payload []*models.ConfigMap `json:"body,omitempty"`
}

// NewGetConfigMapHistoryOK creates GetConfigMapHistoryOK with default headers values
func NewGetConfigMapHistoryOK() *GetConfigMapHistoryOK {

	return &GetConfigMapHistoryOK{}
}

// WithPayload adds the payload to the get config map history o k response
func (o *GetConfigMapHistoryOK) WithPayload(payload []*models.ConfigMap) *GetConfigMapHistoryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config map history o k response
func (o *GetConfigMapHistoryOK) SetPayload(payload []*models.ConfigMap) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigMapHistoryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.ConfigMap, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetConfigMapHistoryDefault Failed

swagger:response getConfigMapHistoryDefault
*/
type GetConfigMapHistoryDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigMapHistoryDefault creates GetConfigMapHistoryDefault with default headers values
func NewGetConfigMapHistoryDefault(code int) *GetConfigMapHistoryDefault {
	if code <= 0 {
		code = 500
	}

	return &GetConfigMapHistoryDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get config map history default response
func (o *GetConfigMapHistoryDefault) WithStatusCode(code int) *GetConfigMapHistoryDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get config map history default response
func (o *GetConfigMapHistoryDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get config map history default response
func (o *GetConfigMapHistoryDefault) WithPayload(payload *models.Error) *GetConfigMapHistoryDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config map history default response
func (o *GetConfigMapHistoryDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigMapHistoryDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
