// Code generated by go-swagger; DO NOT EDIT.

package workload

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetWorkloadHandlerFunc turns a function with the right signature into a get workload handler
type GetWorkloadHandlerFunc func(GetWorkloadParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetWorkloadHandlerFunc) Handle(params GetWorkloadParams) middleware.Responder {
	return fn(params)
}

// GetWorkloadHandler interface for that can handle valid get workload params
type GetWorkloadHandler interface {
	Handle(GetWorkloadParams) middleware.Responder
}

// NewGetWorkload creates a new http.Handler for the get workload operation
func NewGetWorkload(ctx *middleware.Context, handler GetWorkloadHandler) *GetWorkload {
	return &GetWorkload{Context: ctx, Handler: handler}
}

/*GetWorkload swagger:route GET /api/v1/groups/{groupname}/runtime/apps/{appname}/workload workload getWorkload

GetWorkload get workload API

*/
type GetWorkload struct {
	Context *middleware.Context
	Handler GetWorkloadHandler
}

func (o *GetWorkload) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetWorkloadParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
