// Code generated by go-swagger; DO NOT EDIT.

package workload

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetWorkloadHistoryHandlerFunc turns a function with the right signature into a get workload history handler
type GetWorkloadHistoryHandlerFunc func(GetWorkloadHistoryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetWorkloadHistoryHandlerFunc) Handle(params GetWorkloadHistoryParams) middleware.Responder {
	return fn(params)
}

// GetWorkloadHistoryHandler interface for that can handle valid get workload history params
type GetWorkloadHistoryHandler interface {
	Handle(GetWorkloadHistoryParams) middleware.Responder
}

// NewGetWorkloadHistory creates a new http.Handler for the get workload history operation
func NewGetWorkloadHistory(ctx *middleware.Context, handler GetWorkloadHistoryHandler) *GetWorkloadHistory {
	return &GetWorkloadHistory{Context: ctx, Handler: handler}
}

/*GetWorkloadHistory swagger:route GET /api/v1/groups/{groupname}/runtime/apps/{appname}/workload/history workload getWorkloadHistory

GetWorkloadHistory get workload history API

*/
type GetWorkloadHistory struct {
	Context *middleware.Context
	Handler GetWorkloadHistoryHandler
}

func (o *GetWorkloadHistory) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetWorkloadHistoryParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
