// Code generated by go-swagger; DO NOT EDIT.

package workload

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/laincloud/console-api/models"
)

// GetWorkloadHistoryOKCode is the HTTP code returned for type GetWorkloadHistoryOK
const GetWorkloadHistoryOKCode int = 200

/*GetWorkloadHistoryOK Get the workload history of the runtime app

swagger:response getWorkloadHistoryOK
*/
type GetWorkloadHistoryOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Workload `json:"body,omitempty"`
}

// NewGetWorkloadHistoryOK creates GetWorkloadHistoryOK with default headers values
func NewGetWorkloadHistoryOK() *GetWorkloadHistoryOK {

	return &GetWorkloadHistoryOK{}
}

// WithPayload adds the payload to the get workload history o k response
func (o *GetWorkloadHistoryOK) WithPayload(payload []*models.Workload) *GetWorkloadHistoryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get workload history o k response
func (o *GetWorkloadHistoryOK) SetPayload(payload []*models.Workload) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWorkloadHistoryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Workload, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetWorkloadHistoryDefault Failed

swagger:response getWorkloadHistoryDefault
*/
type GetWorkloadHistoryDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetWorkloadHistoryDefault creates GetWorkloadHistoryDefault with default headers values
func NewGetWorkloadHistoryDefault(code int) *GetWorkloadHistoryDefault {
	if code <= 0 {
		code = 500
	}

	return &GetWorkloadHistoryDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get workload history default response
func (o *GetWorkloadHistoryDefault) WithStatusCode(code int) *GetWorkloadHistoryDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get workload history default response
func (o *GetWorkloadHistoryDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get workload history default response
func (o *GetWorkloadHistoryDefault) WithPayload(payload *models.Error) *GetWorkloadHistoryDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get workload history default response
func (o *GetWorkloadHistoryDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWorkloadHistoryDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
