// Code generated by go-swagger; DO NOT EDIT.

package secret

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/laincloud/console-api/models"
)

// GetSecretHistoryOKCode is the HTTP code returned for type GetSecretHistoryOK
const GetSecretHistoryOKCode int = 200

/*GetSecretHistoryOK Get the secret history of the runtime app

swagger:response getSecretHistoryOK
*/
type GetSecretHistoryOK struct {

	/*
	  In: Body
	*/
	Payload [][]*models.Secret `json:"body,omitempty"`
}

// NewGetSecretHistoryOK creates GetSecretHistoryOK with default headers values
func NewGetSecretHistoryOK() *GetSecretHistoryOK {

	return &GetSecretHistoryOK{}
}

// WithPayload adds the payload to the get secret history o k response
func (o *GetSecretHistoryOK) WithPayload(payload [][]*models.Secret) *GetSecretHistoryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get secret history o k response
func (o *GetSecretHistoryOK) SetPayload(payload [][]*models.Secret) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSecretHistoryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([][]*models.Secret, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetSecretHistoryDefault Failed

swagger:response getSecretHistoryDefault
*/
type GetSecretHistoryDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetSecretHistoryDefault creates GetSecretHistoryDefault with default headers values
func NewGetSecretHistoryDefault(code int) *GetSecretHistoryDefault {
	if code <= 0 {
		code = 500
	}

	return &GetSecretHistoryDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get secret history default response
func (o *GetSecretHistoryDefault) WithStatusCode(code int) *GetSecretHistoryDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get secret history default response
func (o *GetSecretHistoryDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get secret history default response
func (o *GetSecretHistoryDefault) WithPayload(payload *models.Error) *GetSecretHistoryDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get secret history default response
func (o *GetSecretHistoryDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSecretHistoryDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
