// Code generated by go-swagger; DO NOT EDIT.

package secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/laincloud/console-api/models"
)

// CreateSecretCreatedCode is the HTTP code returned for type CreateSecretCreated
const CreateSecretCreatedCode int = 201

/*CreateSecretCreated Created

swagger:response createSecretCreated
*/
type CreateSecretCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Secret `json:"body,omitempty"`
}

// NewCreateSecretCreated creates CreateSecretCreated with default headers values
func NewCreateSecretCreated() *CreateSecretCreated {

	return &CreateSecretCreated{}
}

// WithPayload adds the payload to the create secret created response
func (o *CreateSecretCreated) WithPayload(payload *models.Secret) *CreateSecretCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create secret created response
func (o *CreateSecretCreated) SetPayload(payload *models.Secret) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateSecretCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*CreateSecretDefault Failed

swagger:response createSecretDefault
*/
type CreateSecretDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateSecretDefault creates CreateSecretDefault with default headers values
func NewCreateSecretDefault(code int) *CreateSecretDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateSecretDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create secret default response
func (o *CreateSecretDefault) WithStatusCode(code int) *CreateSecretDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create secret default response
func (o *CreateSecretDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create secret default response
func (o *CreateSecretDefault) WithPayload(payload *models.Error) *CreateSecretDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create secret default response
func (o *CreateSecretDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateSecretDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
