// Code generated by go-swagger; DO NOT EDIT.

package secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/laincloud/console-api/models"
)

// CreateOrUpdateSecretsOKCode is the HTTP code returned for type CreateOrUpdateSecretsOK
const CreateOrUpdateSecretsOKCode int = 200

/*CreateOrUpdateSecretsOK OK

swagger:response createOrUpdateSecretsOK
*/
type CreateOrUpdateSecretsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Secret `json:"body,omitempty"`
}

// NewCreateOrUpdateSecretsOK creates CreateOrUpdateSecretsOK with default headers values
func NewCreateOrUpdateSecretsOK() *CreateOrUpdateSecretsOK {

	return &CreateOrUpdateSecretsOK{}
}

// WithPayload adds the payload to the create or update secrets o k response
func (o *CreateOrUpdateSecretsOK) WithPayload(payload []*models.Secret) *CreateOrUpdateSecretsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create or update secrets o k response
func (o *CreateOrUpdateSecretsOK) SetPayload(payload []*models.Secret) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateOrUpdateSecretsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Secret, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*CreateOrUpdateSecretsDefault Failed

swagger:response createOrUpdateSecretsDefault
*/
type CreateOrUpdateSecretsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateOrUpdateSecretsDefault creates CreateOrUpdateSecretsDefault with default headers values
func NewCreateOrUpdateSecretsDefault(code int) *CreateOrUpdateSecretsDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateOrUpdateSecretsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create or update secrets default response
func (o *CreateOrUpdateSecretsDefault) WithStatusCode(code int) *CreateOrUpdateSecretsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create or update secrets default response
func (o *CreateOrUpdateSecretsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create or update secrets default response
func (o *CreateOrUpdateSecretsDefault) WithPayload(payload *models.Error) *CreateOrUpdateSecretsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create or update secrets default response
func (o *CreateOrUpdateSecretsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateOrUpdateSecretsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
