// Code generated by go-swagger; DO NOT EDIT.

package secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateOrUpdateSecretsHandlerFunc turns a function with the right signature into a create or update secrets handler
type CreateOrUpdateSecretsHandlerFunc func(CreateOrUpdateSecretsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateOrUpdateSecretsHandlerFunc) Handle(params CreateOrUpdateSecretsParams) middleware.Responder {
	return fn(params)
}

// CreateOrUpdateSecretsHandler interface for that can handle valid create or update secrets params
type CreateOrUpdateSecretsHandler interface {
	Handle(CreateOrUpdateSecretsParams) middleware.Responder
}

// NewCreateOrUpdateSecrets creates a new http.Handler for the create or update secrets operation
func NewCreateOrUpdateSecrets(ctx *middleware.Context, handler CreateOrUpdateSecretsHandler) *CreateOrUpdateSecrets {
	return &CreateOrUpdateSecrets{Context: ctx, Handler: handler}
}

/*CreateOrUpdateSecrets swagger:route PUT /api/v1/groups/{groupname}/runtime/apps/{appname}/secrets secrets createOrUpdateSecrets

CreateOrUpdateSecrets create or update secrets API

*/
type CreateOrUpdateSecrets struct {
	Context *middleware.Context
	Handler CreateOrUpdateSecretsHandler
}

func (o *CreateOrUpdateSecrets) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateOrUpdateSecretsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
