// Code generated by go-swagger; DO NOT EDIT.

package secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateSecretHandlerFunc turns a function with the right signature into a create secret handler
type CreateSecretHandlerFunc func(CreateSecretParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateSecretHandlerFunc) Handle(params CreateSecretParams) middleware.Responder {
	return fn(params)
}

// CreateSecretHandler interface for that can handle valid create secret params
type CreateSecretHandler interface {
	Handle(CreateSecretParams) middleware.Responder
}

// NewCreateSecret creates a new http.Handler for the create secret operation
func NewCreateSecret(ctx *middleware.Context, handler CreateSecretHandler) *CreateSecret {
	return &CreateSecret{Context: ctx, Handler: handler}
}

/*CreateSecret swagger:route POST /api/v1/groups/{groupname}/runtime/secrets secrets createSecret

CreateSecret create secret API

*/
type CreateSecret struct {
	Context *middleware.Context
	Handler CreateSecretHandler
}

func (o *CreateSecret) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateSecretParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
