// Code generated by go-swagger; DO NOT EDIT.

package secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/laincloud/console-api/models"
)

// DeleteSecretNoContentCode is the HTTP code returned for type DeleteSecretNoContent
const DeleteSecretNoContentCode int = 204

/*DeleteSecretNoContent Deleted

swagger:response deleteSecretNoContent
*/
type DeleteSecretNoContent struct {
}

// NewDeleteSecretNoContent creates DeleteSecretNoContent with default headers values
func NewDeleteSecretNoContent() *DeleteSecretNoContent {

	return &DeleteSecretNoContent{}
}

// WriteResponse to the client
func (o *DeleteSecretNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*DeleteSecretDefault Failed

swagger:response deleteSecretDefault
*/
type DeleteSecretDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteSecretDefault creates DeleteSecretDefault with default headers values
func NewDeleteSecretDefault(code int) *DeleteSecretDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteSecretDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete secret default response
func (o *DeleteSecretDefault) WithStatusCode(code int) *DeleteSecretDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete secret default response
func (o *DeleteSecretDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete secret default response
func (o *DeleteSecretDefault) WithPayload(payload *models.Error) *DeleteSecretDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete secret default response
func (o *DeleteSecretDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteSecretDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
